import tech_specs_api_key from "./utility.js";
import fetch from "node-fetch";
import fs from "fs";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient("https://vegycgafjenigorpmudd.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZ3ljZ2FmamVuaWdvcnBtdWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDQzMDUwMTgsImV4cCI6MjAxOTg4MTAxOH0.n90_rcq--E4wUaQF7863B0Y76PSpYPT5VOl2khawVoA");

const options = {
  method: "GET",
  headers: {
    accept: "application/json",
    "Accept-Encoding": "gzip, deflate",
    Authorization: tech_specs_api_key,
  },
};

const allKeys = [
  //   "status",
  //   "message",
  //   "data_type",
  //   "data_language",
  //   "data_category",
  "data_items_product_dedupe",
  "data_items_product_is_translated",
  "data_items_product_brand",
  "data_items_product_manufacturer",
  "data_items_product_model",
  "data_items_product_version",
  "data_items_product_category",
  "data_items_product_region",
  "data_items_product_country",
  "data_items_product_alias",
  "data_items_product_id",
  "data_items_key_aspects_msrp",
  "data_items_key_aspects_release_date",
  "data_items_key_aspects_color_options",
  "data_items_key_aspects_camera",
  "data_items_key_aspects_os",
  "data_items_key_aspects_processor",
  "data_items_key_aspects_ram",
  "data_items_key_aspects_storage",
  "data_items_key_aspects_wireless_cellular",
  "data_items_key_aspects_additional_features",
  "data_items_image_thumbnail",
  "data_items_image_large",
  "data_items_date_released",
  "data_items_date_announced",
  "data_items_price_msrp",
  "data_items_design_body_height",
  "data_items_design_body_width",
  "data_items_design_body_weight",
  "data_items_design_body_thickness",
  "data_items_design_body_ip_rating",
  "data_items_design_body_colors",
  "data_items_design_body_additional_features",
  "data_items_design_keyboard_keys",
  "data_items_design_keyboard_design",
  "data_items_design_keyboard_backlight",
  "data_items_design_keyboard_ii_keys",
  "data_items_design_keyboard_ii_design",
  "data_items_design_keyboard_ii_backlight",
  "data_items_design_peripheral_peripheral",
  "data_items_display_type",
  "data_items_display_diagonal",
  "data_items_display_resolution_h_x_w",
  "data_items_display_pixel_density",
  "data_items_display_refresh_rate",
  "data_items_display_touch_points",
  "data_items_display_width",
  "data_items_display_height",
  "data_items_display_illumination",
  "data_items_display_dynamic_range",
  "data_items_display_pixel_size",
  "data_items_display_color_depth",
  "data_items_display_subpixels",
  "data_items_display_number_of_colors",
  "data_items_display_screen_to_body_ratio",
  "data_items_display_bezel_width",
  "data_items_display_lcd_mode",
  "data_items_display_touchpoints",
  "data_items_display_glass",
  "data_items_display_notch",
  "data_items_display_punch_hole",
  "data_items_display_module",
  "data_items_display_touch_screen_type",
  "data_items_display_screen_ii_width",
  "data_items_display_screen_ii_height",
  "data_items_display_screen_ii_type",
  "data_items_display_screen_ii_diagonal",
  "data_items_display_screen_ii_illumination",
  "data_items_display_screen_ii_dynamic_range",
  "data_items_display_screen_ii_color_depth",
  "data_items_display_screen_ii_subpixels",
  "data_items_display_screen_ii_number_of_colors",
  "data_items_display_screen_ii_lcd_mode",
  "data_items_display_screen_ii_module",
  "data_items_camera_back_camera_focus",
  "data_items_camera_back_camera_resolution",
  "data_items_camera_back_camera_resolution_h_x_w",
  "data_items_camera_back_camera_video_format",
  "data_items_camera_back_camera_video_resolution",
  "data_items_camera_back_camera_image_format",
  "data_items_camera_back_camera_pixel_size",
  "data_items_camera_back_camera_zoom",
  "data_items_camera_back_camera_flash",
  "data_items_camera_back_camera_aperture_w",
  "data_items_camera_back_camera_features",
  "data_items_camera_back_camera_sensor",
  "data_items_camera_back_camera_equivalent_focal_length",
  "data_items_camera_back_camera_sensor_format",
  "data_items_camera_back_camera_module",
  "data_items_camera_back_camera_minimum_focal_length",
  "data_items_camera_back_camera_aperture_t",
  "data_items_camera_back_camera_ii_focus",
  "data_items_camera_back_camera_ii_resolution",
  "data_items_camera_back_camera_ii_sensor",
  "data_items_camera_back_camera_ii_pixel_size",
  "data_items_camera_back_camera_ii_aperture_w",
  "data_items_camera_back_camera_ii_features",
  "data_items_camera_back_camera_ii_sensor_format",
  "data_items_camera_back_camera_ii_module",
  "data_items_camera_back_camera_ii_equivalent_focal_length",
  "data_items_camera_back_camera_iii_focus",
  "data_items_camera_back_camera_iii_resolution",
  "data_items_camera_back_camera_iii_sensor",
  "data_items_camera_back_camera_iii_pixel_size",
  "data_items_camera_back_camera_iii_aperture_w",
  "data_items_camera_back_camera_iii_features",
  "data_items_camera_back_camera_iii_sensor_format",
  "data_items_camera_back_camera_iii_module",
  "data_items_camera_back_camera_iii_equivalent_focal_length",
  "data_items_camera_back_camera_iv_focus",
  "data_items_camera_back_camera_iv_resolution",
  "data_items_camera_back_camera_iv_sensor",
  "data_items_camera_back_camera_iv_pixel_size",
  "data_items_camera_back_camera_iv_aperture_w",
  "data_items_camera_back_camera_iv_features",
  "data_items_camera_back_camera_iv_sensor_format",
  "data_items_camera_back_camera_iv_module",
  "data_items_camera_back_camera_iv_equivalent_focal_length",
  "data_items_camera_front_camera_focus",
  "data_items_camera_front_camera_resolution",
  "data_items_camera_front_camera_resolution_h_x_w",
  "data_items_camera_front_camera_video_resolution",
  "data_items_camera_front_camera_video_format",
  "data_items_camera_front_camera_image_format",
  "data_items_camera_front_camera_pixel_size",
  "data_items_camera_front_camera_flash",
  "data_items_camera_front_camera_aperture_w",
  "data_items_camera_front_camera_features",
  "data_items_camera_front_camera_sensor",
  "data_items_camera_front_camera_sensor_format",
  "data_items_camera_front_camera_module",
  "data_items_camera_front_camera_minimum_focal_length",
  "data_items_camera_front_camera_ii_focus",
  "data_items_camera_front_camera_ii_resolution",
  "data_items_camera_front_camera_ii_resolution_h_x_w",
  "data_items_camera_front_camera_ii_video_resolution",
  "data_items_camera_front_camera_ii_video_format",
  "data_items_camera_front_camera_ii_image_format",
  "data_items_camera_front_camera_ii_pixel_size",
  "data_items_camera_front_camera_ii_flash",
  "data_items_camera_front_camera_ii_aperture_w",
  "data_items_camera_front_camera_ii_features",
  "data_items_camera_front_camera_ii_sensor",
  "data_items_camera_front_camera_ii_sensor_format",
  "data_items_camera_front_camera_ii_module",
  "data_items_camera_front_camera_ii_minimum_focal_length",
  "data_items_inside_software_os",
  "data_items_inside_software_kernel_version",
  "data_items_inside_software_os_version",
  "data_items_inside_software_additional_features",
  "data_items_inside_processor_cpu",
  "data_items_inside_processor_cpu_clock_speed",
  "data_items_inside_processor_gpu",
  "data_items_inside_processor_gpu_clock_speed",
  "data_items_inside_processor_gpu_dedicated_memory",
  "data_items_inside_processor_gpu_framebuffer",
  "data_items_inside_ram_type",
  "data_items_inside_ram_capacity",
  "data_items_inside_ram_clock_speed",
  "data_items_inside_ram_module",
  "data_items_inside_storage_type",
  "data_items_inside_storage_capacity",
  "data_items_inside_storage_expansion",
  "data_items_inside_storage_module",
  "data_items_inside_storage_bus_speed",
  "data_items_inside_audio_chip",
  "data_items_inside_audio_adc_resolution",
  "data_items_inside_audio_adc_frequency",
  "data_items_inside_audio_dac_frequency",
  "data_items_inside_audio_dac_resolution",
  "data_items_inside_audio_channel",
  "data_items_inside_audio_output",
  "data_items_inside_audio_hearing_aid_compatibility",
  "data_items_inside_audio_microphone_input",
  "data_items_inside_audio_microphone",
  "data_items_inside_audio_av_out",
  "data_items_inside_audio_av_resolution",
  "data_items_inside_audio_loudspeaker_power",
  "data_items_inside_cellular_sim_chip",
  "data_items_inside_cellular_sim_slot",
  "data_items_inside_cellular_sim_frequencies",
  "data_items_inside_cellular_sim_mobile_data",
  "data_items_inside_cellular_sim_ii_slot",
  "data_items_inside_cellular_sim_ii_frequencies",
  "data_items_inside_cellular_sim_ii_mobile_data",
  "data_items_inside_cellular_sim_ii_module",
  "data_items_inside_cellular_dual_sim_type",
  "data_items_inside_cellular_carrier",
  "data_items_inside_cellular_generation",
  "data_items_inside_cellular_sim_type",
  "data_items_inside_wireless_bluetooth_version",
  "data_items_inside_wireless_bluetooth_module",
  "data_items_inside_wireless_bluetooth_profiles",
  "data_items_inside_wireless_wifi",
  "data_items_inside_wireless_wifi_features",
  "data_items_inside_wireless_experiences",
  "data_items_inside_wireless_wlan_module",
  "data_items_inside_wireless_Wman",
  "data_items_inside_ports_usb_type",
  "data_items_inside_ports_usb_version",
  "data_items_inside_ports_usb_features",
  "data_items_inside_ports_usb_type_port_ii",
  "data_items_inside_ports_usb_features_port_ii",
  "data_items_inside_ports_usb_version_port_ii",
  "data_items_inside_ports_ethernet_standard",
  "data_items_inside_ports_ethernet",
  "data_items_inside_ports_serial_connector",
  "data_items_inside_ports_serial_bit_rate",
  "data_items_inside_ports_serial_standard",
  "data_items_inside_ports_modem_standard",
  "data_items_inside_ports_modem",
  "data_items_inside_ports_fax_modem_standard",
  "data_items_inside_battery_type",
  "data_items_inside_battery_cell_i",
  "data_items_inside_battery_cell_ii",
  "data_items_inside_battery_power_ic",
  "data_items_inside_battery_capacity",
  "data_items_inside_battery_voltage",
  "data_items_inside_battery_energy",
  "data_items_inside_battery_Wireless_charging",
  "data_items_inside_battery_charging_power",
  "data_items_inside_battery_Wireless_charging_power",
  "data_items_inside_battery_style",
  "data_items_inside_battery_talk_time",
  "data_items_inside_battery_standby_time",
  "data_items_inside_battery_standby_current_consumption",
  "data_items_inside_battery_current",
  "data_items_inside_battery_life",
  "data_items_inside_location_chip",
  "data_items_inside_location_additional_features",
  "data_items_inside_location_parallel_gps_channels",
  "data_items_inside_sensors_sensors",
  "data_items_inside_sar_head_usa",
  "data_items_inside_sar_head_eu",
  "data_items_inside_sar_body_usa",
  "data_items_inside_sar_body_eu",
  "data_items_inside_sar_hotspot_usa",
  "data_items_no_expansion",
  "data_items_no_fm_radio",
];

async function getPhoneFromApi(id) {
  fetch(`https://api.techspecs.io/v4/product/detail?productId=${id}`, options)
    .then((response) => response.json())
    .then((response) => {
      const flattenedData = deepKeys(response.data.items[0]);
      const filteredData = Object.keys(flattenedData)
        .filter((key) => allKeys.includes(key))
        .reduce((obj, key) => {
          obj[key] = flattenedData[key];
          return obj;
        }, {});
      return filteredData;
    })
    .then((filteredData) => {
      supabase
        .from("sql_data4")
        .upsert([filteredData])
        .then((response) => {
          console.log(response);
        })
        .catch((err) => {
          console.log(err);
        });
    })

    .catch((err) => console.log(err));
}

//const deepKeys = (o) => (Array.isArray(o) ? o.flatMap(deepKeys) : Object(o) === o ? Object.entries(o).flatMap(([k, v]) => [k, ...deepKeys(v)]) : []);
//source: https://stackoverflow.com/questions/70713850/recursively-flatten-a-deeply-nested-mix-of-objects-and-arrays

const deepKeys = (obj, path = "") => {
  if (!(obj instanceof Object)) return { [`data_items_${path}`]: obj };
  return Object.keys(obj).reduce((output, key) => {
    const newPath = path ? `${path}_${key}`.toLowerCase().replace(/[()]/g, "") : key;
    return { ...output, ...deepKeys(obj[key], newPath) };
  }, {});
};

export default getPhoneFromApi;
